## Final Project : Retail BI Chatbot (Telegram)

In [1]:
pip install pandas langchain langchain-community langchain-google-genai chromadb pypdf python-telegram-bot nest_asyncio

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.2.15)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.1)
Requirement already satisfied: langchain-google-genai in /usr/local/lib/python3.12/dist-packages (4.2.2)
Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.9)
Requirement already satisfied: pypdf in /usr/local/lib/python3.12/dist-packages (6.11.0)
Requirement already satisfied: python-telegram-bot in /usr/local/lib/python3.12/dist-packages (22.7)
Requirement already satisfied: nest_asyncio in /usr/local/lib/python3.12/dist-packages (1.6.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.2.10 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.3.3)
Requirement already satisfied: langgraph<1.2.0,>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.1.9)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.12.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.7)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.49)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.33.1)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.13.5)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.14.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.7.34)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: filetype<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (1.2.0)
Requirement already satisfied: google-genai<2.0.0,>=1.65.0 in /usr/local/lib/python3.12/dist-packages (from langchain-google-genai) (1.68.0)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.5.0)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.46.0)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.26.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.41.1)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.80.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.24.2)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (35.0.0)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.8)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.23.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.1)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community) (0.9.0)
Requirement already satisfied: anyio<5.0.0,>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.65.0->langchain-google-genai) (4.13.0)
Requirement already satisfied: google-auth<3.0.0,>=2.47.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.65.0->langchain-google-genai) (2.47.0)
Requirement already satisfied: websockets<17.0,>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.65.0->langchain-google-genai) (15.0.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.65.0->langchain-google-genai) (1.9.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from google-genai<2.0.0,>=1.65.0->langchain-google-genai) (1.3.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.4.22)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.13)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.30.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community) (1.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.10 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.0.15)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.2.10->langchain) (0.14.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=2.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (4.0.2)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.9 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (1.0.10)
Requirement already satisfied: langgraph-sdk<0.4.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (0.3.13)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.2.0,>=1.1.5->langchain) (3.6.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.1)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.74.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-proto==1.41.1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.41.1)
Requirement already satisfied: opentelemetry-semantic-conventions==0.62b1 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.62b1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.7)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community) (3.4.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.11.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.6.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.7.1)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.1.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.65.0->langchain-google-genai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.65.0->langchain-google-genai) (4.9.1)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.4.3)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.1)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.2.10->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=2.1.0->langgraph<1.2.0,>=1.1.5->langchain) (1.12.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community) (1.1.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.47.0->google-auth[requests]<3.0.0,>=2.47.0->google-genai<2.0.0,>=1.65.0->langchain-google-genai) (0.6.3)

In [2]:
import pandas as pd

df = pd.read_csv("retail_sales_dataset.csv", sep=";")
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,01/01/2026,CUST1000,Male,41,Clothing,3,300,900
1,2,01/01/2026,CUST001,Male,46,Beauty,3,500,1500
2,3,01/01/2026,CUST002,Female,40,Clothing,4,300,1200
3,4,01/01/2026,CUST003,Male,47,Clothing,2,30,60
4,5,01/01/2026,CUST004,Male,27,Clothing,2,25,50

In [3]:
df['Year'] = df['Date'].str.split('/').str[2]
df['Month'] = df['Date'].str.split('/').str[1]
df['Day'] = df['Date'].str.split('/').str[0]

df["Month_Name"] = pd.to_datetime(df["Month"], format="%m").dt.month_name()
df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Year,Month,Day,Month_Name
0,1,01/01/2026,CUST1000,Male,41,Clothing,3,300,900,2026,01,01,January
1,2,01/01/2026,CUST001,Male,46,Beauty,3,500,1500,2026,01,01,January
2,3,01/01/2026,CUST002,Female,40,Clothing,4,300,1200,2026,01,01,January
3,4,01/01/2026,CUST003,Male,47,Clothing,2,30,60,2026,01,01,January
4,5,01/01/2026,CUST004,Male,27,Clothing,2,25,50,2026,01,01,January

In [4]:
# Summarize the insight from dataset as insight knowledge

total_sales = df["Total Amount"].sum()

list_product = df["Product Category"].unique()

top_product = (
    df.groupby("Product Category")["Total Amount"]
    .sum()
    .idxmax()
)

top_product_january =(
    df[df["Month_Name"] == "January"].groupby("Product Category")["Total Amount"]
    .sum()
    .idxmax()
)

top_product_february =(
    df[df["Month_Name"] == "February"].groupby("Product Category")["Total Amount"]
    .sum()
    .idxmax()
)

top_product_march =(
    df[df["Month_Name"] == "March"].groupby("Product Category")["Total Amount"]
    .sum()
    .idxmax()
)

top_product_april =(
    df[df["Month_Name"] == "April"].groupby("Product Category")["Total Amount"]
    .sum()
    .idxmax()
)

top_product_may =(
    df[df["Month_Name"] == "May"].groupby("Product Category")["Total Amount"]
    .sum()
    .idxmax()
)

total_transactions = df["Transaction ID"].count()

female_customer = (
    df[df["Gender"] == "Female"]["Customer ID"]
    .count()
)

male_customer = (
    df[df["Gender"] == "Male"]["Customer ID"]
    .count()
)

all_customer = df["Customer ID"].count()

female_spending = (
    df[df["Gender"] == "Female"]["Total Amount"]
    .sum()
)

male_spending = (
    df[df["Gender"] == "Male"]["Total Amount"]
    .sum()
)

avg_age = df["Age"].mean()
female_avg_age = df[df["Gender"] == "Female"]["Age"].mean()
male_avg_age = df[df["Gender"] == "Male"]["Age"].mean()


beauty_avg_age_female = (
    df[(df["Gender"] == "Female") & (df["Product Category"] == "Beauty")]["Age"]
    .mean()
)
beauty_avg_age_male = (
    df[(df["Gender"] == "Male") & (df["Product Category"] == "Beauty")]["Age"]
    .mean()
)

clothing_avg_age_female = (
    df[(df["Gender"] == "Female") & (df["Product Category"] == "Clothing")]["Age"]
    .mean()
)
clothing_avg_age_male = (
    df[(df["Gender"] == "Male") & (df["Product Category"] == "Clothing")]["Age"]
    .mean()
)

electronics_avg_age_female = (
    df[(df["Gender"] == "Female") & (df["Product Category"] == "Electronics")]["Age"]
    .mean()
)
electronics_avg_age_male = (
    df[(df["Gender"] == "Male") & (df["Product Category"] == "Electronics")]["Age"]
    .mean()
)


## Top Sales of product
top_sales_beauty_period =(
    df[df["Product Category"] == "Beauty"].groupby("Month_Name")["Total Amount"]
    .sum()
    .idxmax()
)
top_sales_clothing_period =(
    df[df["Product Category"] == "Clothing"].groupby("Month_Name")["Total Amount"]
    .sum()
    .idxmax()
)
top_sales_electronics_period =(
    df[df["Product Category"] == "Electronics"].groupby("Month_Name")["Total Amount"]
    .sum()
    .idxmax()
)

# Product Sales
beauty_sales = (
    df[df["Product Category"] == "Beauty"]["Total Amount"]
    .sum()
)
clothing_sales = (
    df[df["Product Category"] == "Clothing"]["Total Amount"]
    .sum()
)
electronics_sales = (
    df[df["Product Category"] == "Electronics"]["Total Amount"]
    .sum()
)

beauty_avg_price = df[df["Product Category"] == "Beauty"]["Price per Unit"].mean()
clothing_avg_price = df[df["Product Category"] == "Clothing"]["Price per Unit"].mean()
electronics_avg_price = df[df["Product Category"] == "Electronics"]["Price per Unit"].mean()

january_total_sales = df[df["Month_Name"] == "January"]["Total Amount"].sum()
february_total_sales = df[df["Month_Name"] == "February"]["Total Amount"].sum()
march_total_sales = df[df["Month_Name"] == "March"]["Total Amount"].sum()
april_total_sales = df[df["Month_Name"] == "April"]["Total Amount"].sum()
may_total_sales = df[df["Month_Name"] == "May"]["Total Amount"].sum()

#Beauty
january_total_sales_beauty = df[(df["Month_Name"] == "January") & (df["Product Category"] == "Beauty")]["Total Amount"].sum()
february_total_sales_beauty = df[(df["Month_Name"] == "February") & (df["Product Category"] == "Beauty")]["Total Amount"].sum()
march_total_sales_beauty = df[(df["Month_Name"] == "March") & (df["Product Category"] == "Beauty")]["Total Amount"].sum()
april_total_sales_beauty = df[(df["Month_Name"] == "April") & (df["Product Category"] == "Beauty")]["Total Amount"].sum()
may_total_sales_beauty = df[(df["Month_Name"] == "May") & (df["Product Category"] == "Beauty")]["Total Amount"].sum()

#Clothing
january_total_sales_clothing = df[(df["Month_Name"] == "January") & (df["Product Category"] == "Clothing")]["Total Amount"].sum()
february_total_sales_clothing = df[(df["Month_Name"] == "February") & (df["Product Category"] == "Clothing")]["Total Amount"].sum()
march_total_sales_clothing = df[(df["Month_Name"] == "March") & (df["Product Category"] == "Clothing")]["Total Amount"].sum()
april_total_sales_clothing = df[(df["Month_Name"] == "April") & (df["Product Category"] == "Clothing")]["Total Amount"].sum()
may_total_sales_clothing = df[(df["Month_Name"] == "May") & (df["Product Category"] == "Clothing")]["Total Amount"].sum()

#Electronics
january_total_sales_elec = df[(df["Month_Name"] == "January") & (df["Product Category"] == "Electronics")]["Total Amount"].sum()
february_total_sales_elec = df[(df["Month_Name"] == "February") & (df["Product Category"] == "Electronics")]["Total Amount"].sum()
march_total_sales_elec = df[(df["Month_Name"] == "March") & (df["Product Category"] == "Electronics")]["Total Amount"].sum()
april_total_sales_elec = df[(df["Month_Name"] == "April") & (df["Product Category"] == "Electronics")]["Total Amount"].sum()
may_total_sales_elec = df[(df["Month_Name"] == "May") & (df["Product Category"] == "Electronics")]["Total Amount"].sum()

In [5]:
from langchain_community.document_loaders import PyPDFLoader

loader_cus = PyPDFLoader("Customer Segmentation Knowledge Retail.pdf")
pdf_docs_cus = loader_cus.load()

loader_bea = PyPDFLoader("Beauty Knowledge Retail.pdf")
pdf_docs_bea = loader_bea.load()

loader_clo = PyPDFLoader("Clothing Knowledge Retail.pdf")
pdf_docs_clo = loader_clo.load()

loader_ele = PyPDFLoader("Electronics Knowledge Retail.pdf")
pdf_docs_ele = loader_ele.load()

In [6]:
from langchain_core.documents import Document

insight_docs = [
  Document(
        page_content="Berikut ini adalah catatan customer yang terjadi sepanjang 2026 sebagai berikut:"),
  Document(
        page_content=f"""Total customer keseluruhan adalah {all_customer} dengan pembagian sebagai berikut."""),
  Document(
        page_content=f"""Total customer perempuan adalah {female_customer} dan Total customer laki-laki adalah {male_customer} ."""),
  Document(
        page_content=f"""Rata-rata umur customer adalah {avg_age:.1f} tahun."""),
   Document(
        page_content=f"""Rata-rata umur customer perempuan adalah {female_avg_age:.1f} tahun, sedangkan rata-rata umur customer laki-laki adalah {male_avg_age:.1f} tahun ."""),
     Document(
        page_content="Berikut ini adalah catatan Sales secara keseluruhan yang terjadi sepanjang 2026 sebagai berikut:"),
      Document(
        page_content=f"""Total Sales keseluruhan adalah ${total_sales}."""),
   Document(
        page_content=f"""list produk yang terjual sepanjang tahun 2026 antara lain {list_product[0]}, {list_product[1]}, dan {list_product[2]}."""),
   Document(
        page_content=f"""Customer Perempuan menghabiskan belanja sebesar ${female_spending} sedangkan laki-laki menghabiskan belanja sebesar {male_spending}."""),
     Document(
        page_content=f"""Total Sales yang terjadi pada bulan Januari sebesar ${january_total_sales}, Februari sebesar ${february_total_sales}, ${march_total_sales}, April sebesar ${april_total_sales}, Mei sebesar ${may_total_sales}."""),
      Document(
        page_content=f"""Total sales pada produk kategori Beauty sebesar ${beauty_sales:.1f},  kategori Clothing sebesar ${clothing_sales:.1f},  kategori Electronics sebesar ${electronics_sales:.1f}."""),
     Document(
        page_content=f"""Total transaksi secara keseluruhan adalah {total_transactions}."""),
     Document(
        page_content=f"""Categori produk dengan penjualan tertinggi adalah {top_product}."""),
     Document(
         page_content=f"""Top Sales pada bulan Januari adalah {top_product_january} ,bulan Februari adalah {top_product_february}, bulan Maret adalah {top_product_march},bulan April adalah {top_product_april}, bulan Mei adalah {top_product_may}."""),
    Document(
        page_content=f"""Total penjualan pada bulan januari untuk kategori produk Beauty adalah ${january_total_sales_beauty}, kategori produk Clothing adalah ${january_total_sales_clothing}, kategori produk Electronics adalah ${january_total_sales_elec}"""),
  Document(
        page_content=f"""Total penjualan pada bulan Februari untuk kategori produk Beauty adalah ${february_total_sales_beauty}, kategori produk Clothing adalah ${february_total_sales_clothing}, kategori produk Electronics adalah ${february_total_sales_elec}"""),
  Document(
        page_content=f"""Total penjualan pada bulan Maret untuk kategori produk Beauty adalah ${march_total_sales_beauty}, kategori produk Clothing adalah ${march_total_sales_clothing}, kategori produk Electronics adalah ${march_total_sales_elec}"""),
  Document(
        page_content=f"""Total penjualan pada bulan April untuk kategori produk Beauty adalah ${april_total_sales_beauty}, kategori produk Clothing adalah ${april_total_sales_clothing}, kategori produk Electronics adalah ${april_total_sales_elec}"""),
  Document(
        page_content=f"""Total penjualan pada bulan Mei untuk kategori produk Beauty adalah ${may_total_sales_beauty}, kategori produk Clothing adalah ${may_total_sales_clothing}, kategori produk Electronics adalah ${may_total_sales_elec}"""),
     Document(
         page_content=f"""Top penjualan pada produk kategori Beauty terjadi pada bulan {top_sales_beauty_period}, lalu pada kategori Clothing terjadi pada bulan {top_sales_clothing_period} dan kategori Electronics pada {top_sales_electronics_period}."""),
     Document(
        page_content=f"""Rata-rata harga penjualan pada produk kategori Beauty sebesar ${beauty_avg_price:.1f}, lalu pada kategori Clothing sebesar ${clothing_avg_price:.1f}, dan pada kategori Electronics sebesar ${electronics_avg_price:.1f}."""),
     Document(
         page_content=f"""Rata-rata umur customer yang membeli produk kategori Beauty pada gender perempuan adalah {beauty_avg_age_female} dan rata-rata umur laki-laki adalah {beauty_avg_age_male}. Lalu, Rata-rata umur customer yang membeli produk kategori Clothing pada gender perempuan adalah {clothing_avg_age_female} dan rata-rata umur laki-laki adalah {clothing_avg_age_male}. Dan terakhir Rata-rata umur customer yang membeli produk kategori Electronics pada gender perempuan adalah {electronics_avg_age_female} dan rata-rata umur laki-laki adalah {electronics_avg_age_male}.""")
]

In [7]:
#gabungkan dokumen insight dan knowledge
docs = insight_docs + pdf_docs_cus + pdf_docs_bea + pdf_docs_clo + pdf_docs_ele

In [8]:
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from google.colab import userdata

api_key = userdata.get("GEMINI_API")

embeddings = GoogleGenerativeAIEmbeddings(
    model="gemini-embedding-2",
    google_api_key=api_key
)

In [9]:
from langchain_community.vectorstores import Chroma
import os

persist_dir = "chroma_db"

vectorstore = Chroma.from_documents(
    documents=docs,
    embedding=embeddings,
    persist_directory=persist_dir
)

retriever = vectorstore.as_retriever(search_kwargs={"k": 8})

In [10]:
from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    google_api_key=api_key,
    temperature=0.2,
    top_p = 0.8
)

In [11]:
def ask(question):

    docs = retriever.invoke(question)

    context = "\n- ".join([d.page_content for d in docs])

    prompt = f"""
You are a Business Intelligence Analyst specializing in retail sales.

Rules:
- Translate explanations into professional Indonesian language.
- Always answer in natural Bahasa Indonesia even if the context is in English.
- Always say halo for first response.
- Use ONLY the provided context and data.
- Do not hallucinate or invent numbers.
- Respond naturally like a BI analyst explaining insights to a team.
- Keep the response concise, clear, and conversational.
- Use business reasoning when relevant.
- Provide practical suggestions naturally.
- Avoid rigid templates, markdown formatting, headers, or excessive bullet points suchas **bold**.
- Analyze relationships between the provided metrics and summaries when relevant.
- Explain possible correlations between customer behavior, product performance, and sales trends.
- Use business reasoning carefully based on the available data.
- Do not invent unsupported facts.
- Keep the response under 5 short sentences.
- If the data is insufficient, clearly mention the limitation.

DATA:
{context}

QUESTION:
{question}

Answer clearly and analytically.
"""

    response = llm.invoke(prompt).content

    return response[:3500]

In [13]:
print(ask("Bisakah kamu jelaskan faktor faktor memepengaruhi penjualan produk beauty?"))

Halo. Penjualan produk *beauty* sangat dipengaruhi oleh strategi *omnichannel* yang mengintegrasikan pengalaman sensorik di toko fisik dengan kemudahan belanja *online*. Peran staf yang berpengetahuan dan rekomendasi personal juga krusial dalam membangun kepercayaan pelanggan dan mendorong pembelian impulsif. Tren *premiumization* serta permintaan kuat pada kategori *fragrance* dan *skincare* menjadi pendorong pertumbuhan signifikan, didukung oleh rata-rata harga jual produk *beauty* yang tertinggi ($184.1) di antara kategori lain. Selain itu, pemanfaatan media sosial dan *digital influencer* sangat penting untuk memahami dan membentuk permintaan konsumen. Puncak penjualan di bulan Februari juga menunjukkan adanya pola musiman yang perlu diperhatikan.

In [12]:
import nest_asyncio
nest_asyncio.apply()

from telegram import Update
from telegram.ext import ApplicationBuilder, MessageHandler, ContextTypes, filters

BOT_TOKEN = userdata.get("TOKEN_TELE_BOT")

In [ ]:
"""
list pertanyaan:
berapa total sales di tahun 2026?

pada bulan februari produk apa dengan penjualan tertinggi dan aspek apa saja yang mempengaruhi kenaikanny
Aspek apa saja yang mempengaruhi penjualan pada produk clothing?

"""

'\nlist pertanyaan:\nberapa total sales di tahun 2026?\n\n\n'

In [13]:
async def reply(update: Update, context: ContextTypes.DEFAULT_TYPE):

    user_text = update.message.text

    # typing effect (biar keliatan AI)
    await context.bot.send_chat_action(
        chat_id=update.effective_chat.id,
        action="typing"
    )

    answer = ask(user_text)

    await update.message.reply_text(answer)

In [ ]:
# Run it code if you want to interact in telegram chatbot (Sometimes this command will be error regarding API limitattion because it's free API key
app = ApplicationBuilder().token(BOT_TOKEN).build()

app.add_handler(
    MessageHandler(filters.TEXT & ~filters.COMMAND, reply)
)

print("AI BI Chatbot is running...")

app.run_polling()

In [ ]:
# Notes:
#when run comamnd above and show "AI BI Chatbot is running..., you can start use telegram to interact with chatbot"